"""item model

Revision ID: 938b6958d8a0
Revises: c8e907cec20f
Create Date: 2025-05-26 18:10:00.767520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938b6958d8a0'
down_revision: Union[str, None] = 'c8e907cec20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('float_id', sa.Integer(), nullable=True),
    sa.Column('float_value', sa.Float(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ITEM_SOLD', 'ITEM_STORAGE', 'ITEM_LISTED', name='itemstatus'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['game_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['float_id'], ['item_floats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['item_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_purchase_price'), ['purchase_price'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_sale_price'), ['sale_price'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_title'))
        batch_op.drop_index(batch_op.f('ix_items_status'))
        batch_op.drop_index(batch_op.f('ix_items_sale_price'))
        batch_op.drop_index(batch_op.f('ix_items_purchase_price'))

    op.drop_table('items')
    # ### end Alembic commands ###
